name: Update Threat Lists

on:
  schedule:
    - cron: '0 3 * * 0'  # Every Sunday at 03:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run domain generator
        run: python generate_lists.py

      - name: Commit and push updated lists
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add domains/*.txt README.md
          git commit -m "Update threat lists"
          git push
        continue-on-error: true
